### PR TITLE
WIP First stab at integration testing

### PR DESCRIPTION
**Pull request by fungusakafungus**
- use serverspec
- throw away its default config
- use Net::SSH to run puppet on host

### CODE REVIEW

**Comment by nightlyone** [comment]
isn't it finished already? https://github.com/Jimdo/puppet-skeleton

**Comment by zined** [comment]
was about to share the same link, @nightlyone.

@fungusakafungus https://github.com/Jimdo/puppet-beanstalkd and https://github.com/Jimdo/puppet-hiera are actually based on https://github.com/Jimdo/puppet-skeleton

**Comment by fungusakafungus** [comment]
@nightlyone @zined Well, it is not finished for this project and I'm struggling to get puppet-skeleton into here.

My problems with it:
- I can't run virtualbox at home
- puppet-skeleton makes assumptions about the project structure
- puppet-skeleton involves copy-pasting lots of code into project's Rakefile

**Comment by nightlyone** [comment]
Hi @fungusakafungus 

do you plan to continue or close this pull-request? 😁

**Pull request closed without merging**
